name: 'PackTest Runner'
description: 'Runs datapack tests using PackTest'
author: CarbonSmasher
branding:
  icon: 'check'
  color: 'green'
inputs:
  packs:
    description: 'Paths to packs to test, separated by commas'
    required: true
  minecraft-version:
    description: 'Minecraft version to use. Defaults to 1.20.4'
    required: false
    default: '1.20.4'
  packtest-url:
    description: 'URL to the PackTest mod to use. Defaults to URL for the latest version for the specified Minecraft version'
    required: false
    default: 'latest'
  fabric-api-url:
    description: 'URL to the Fabric API mod to use. Defaults to URL for the latest version for the specified Minecraft version'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Cache executable
      id: cache-executable
      uses: actions/cache@v3
      with:
        path: /packtest_runner/target/debug/packtest_runner
        key: packtest_runner_executable_${{ env.ACTION_REF }}
      env:
        ACTION_REF: ${{ github.action_ref }}
    - uses: actions/checkout@v1
    - name: Build and run
      if: steps.cache-executable.outputs.cache-hit != 'true'
      uses: ./run.yml
      with:
        build: build
        packs: ${{ inputs.packs }}
        minecraft-version: ${{ inputs.minecraft-version }}
        packtest-url: ${{ inputs.packtest-url }}
        fabric-api-url: ${{ inputs.fabric-api-url }}
    - name: Run without building
      if: steps.cache-executable.outputs.cache-hit == 'true'
      uses: ./run.yml
      with:
        build: nobuild
        packs: ${{ inputs.packs }}
        minecraft-version: ${{ inputs.minecraft-version }}
        packtest-url: ${{ inputs.packtest-url }}
        fabric-api-url: ${{ inputs.fabric-api-url }}
