name: 'PackTest Runner'
description: 'Runs datapack tests using PackTest'
inputs:
  packs:
    description: 'Paths to packs to test, separated by commas'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.packs }}
